### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by 78fatemanazari** [78fatemanazari/ruby-capstone#9]
### Github Project Link:
- https://github.com/78fatemanazari/ruby-capstone/projects/1

### We are 3 collaborating in this capstone project(Here are the Github links):

- MR. FRANCIS ANDOH: https://github.com/CobbyElsonfx (Team member #3)
- Md.Rafiduzzaman Nahin: https://github.com/Rafiduzzaman (Team member #2)
- Fatema Nazari : https://github.com/78fatemanazari (Team member #1)

**Comment by Ibizugbe** [comment]
Hi @78fatemanazari  @Rafiduzzaman  @CobbyElsonfx 👋🏼👋🏼👋🏼, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Link to github project has been sent👍🏼.
- [x] Each card is properly assigned👍🏼.
- [x] Issue is well documented👍🏼.


## Required Changes ♻️

- [ ] Just as required in this milestone, Kindly ensure all requirements are captured as separate tasks and should have a separate card. apart from this being a requirement, it breaks the team task into smaller components which makes it easier to track the progress of each team member😉.
in doing this, Please kindly ensure all requirements are captured😉.
<img width="1095" alt="image" src="https://github.com/78fatemanazari/ruby-capstone/assets/64643995/82edffa6-1644-493f-884a-3c239bbd96f6">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] In describing the number of points assigned to a card, kindly consider adding `pt` or `pts` as the case may be to the number. hence, instead of `5`, you have `5pts`😉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by 78fatemanazari** [comment]
Hi dear code reviewer!
So sorry for asking. Can you explain more about the required changes?
Because, in the template there were 4 cards and I have assigned 3 tasks to
my partners and myself, and one task is a group task. So, which tasks I
should capture.
Thanks!

**Comment by Ibizugbe** [comment]
Hello @78fatemanazari , It's fine you are asking👍🏼. Sorry, I am replying late by the way.  What I am saying is each [requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) given, should have a card to represent it, then each cards can be assigned to the respective team member concerned. This way, you will have many cards representing the various requirements and breaking the project tasks into smaller bits.

A good way to implement this is, each of the major requirements will have their respective card.

example.
for group task...
```
card 1: Create Item class

description: Create Item class in a separate .rb file.

```

```
card 2: All Item class properties visible in the diagram should be defined and set up in the constructor method

description: All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.

```

```
card 4: Implement methods

description: 
can_be_archived?() in the Item class
should return true if published_date is older than 10 years
otherwise, it should return false
move_to_archive() in the Item class
should reuse can_be_archived?() method
should change the archived property to true if the result of the can_be_archived?() method is true
should do nothing if the result of the can_be_archived?() method is false

```

This way, we can have 6 different cards assigned as group tasks but covering the six major requirements for group tasks.

That way, team member 1 will have about 9 cards for the 9 major requirements
team member 2 will have about 9 cards for the 9 major requirements
team member 3 will also have about 9 cards for the 9 major requirements

kindly ensure each card has a description😉.

If you are still confused, you can reach out on slack👍🏼.

Happy coding👍🏼.

**Comment by Alfredbis29** [comment]
# STATUS: APPROVED   
 ## Hi  @Ibizugbe , @Rafiduzzaman , @CobbyElsonfx 
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Good Job :+1:
 
 Now you can merge this branch and move on 1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions

- [x] N/A

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
